# Generated by Django 4.2.4 on 2023-08-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board_app', '0002_rename_user_message_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='messageAuthor',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='user',
            new_name='responseAuthor',
        ),
    ]
